export const recipes = [
  {
    id: "1",
    title: "Creamy Garlic Parmesan Pasta",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 25,
    rating: 4.8,
    category: "cooking",
    trending: true,
    ingredients: [
      "8 oz fettuccine pasta",
      "2 tbsp butter",
      "4 cloves garlic, minced",
      "1 cup heavy cream",
      "1 cup grated Parmesan cheese",
      "Salt and pepper to taste",
      "Fresh parsley for garnish",
    ],
    instructions: [
      "Cook pasta according to package directions. Drain and set aside.",
      "In a large skillet, melt butter over medium heat. Add minced garlic and sauté for 1-2 minutes until fragrant.",
      "Pour in heavy cream and bring to a simmer. Cook for 3-4 minutes until slightly thickened.",
      "Reduce heat to low and gradually whisk in Parmesan cheese until melted and smooth.",
      "Season with salt and pepper to taste.",
      "Add cooked pasta to the sauce and toss until well coated.",
      "Garnish with fresh parsley and additional Parmesan if desired. Serve immediately.",
    ],
  },
  {
    id: "2",
    title: "Chocolate Chip Cookies",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 35,
    rating: 4.9,
    category: "baking",
    trending: true,
    ingredients: [
      "2 1/4 cups all-purpose flour",
      "1 tsp baking soda",
      "1 tsp salt",
      "1 cup unsalted butter, softened",
      "3/4 cup granulated sugar",
      "3/4 cup packed brown sugar",
      "2 large eggs",
      "2 tsp vanilla extract",
      "2 cups chocolate chips",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line baking sheets with parchment paper.",
      "In a small bowl, whisk together flour, baking soda, and salt.",
      "In a large bowl, beat butter, granulated sugar, and brown sugar until creamy.",
      "Add eggs one at a time, beating well after each addition. Stir in vanilla.",
      "Gradually beat in flour mixture. Stir in chocolate chips.",
      "Drop by rounded tablespoons onto prepared baking sheets.",
      "Bake for 9-11 minutes or until golden brown. Cool on baking sheets for 2 minutes, then transfer to wire racks.",
    ],
  },
  {
    id: "3",
    title: "Party Punch Bowl",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 15,
    rating: 4.7,
    category: "party",
    trending: true,
    ingredients: [
      "2 liters lemon-lime soda",
      "1 can (46 oz) pineapple juice",
      "1 quart strawberry ice cream",
      "1 bag frozen mixed berries",
      "Fresh mint leaves for garnish",
    ],
    instructions: [
      "In a large punch bowl, combine lemon-lime soda and pineapple juice.",
      "Add scoops of strawberry ice cream to float on top.",
      "Add frozen mixed berries.",
      "Garnish with fresh mint leaves.",
      "Serve immediately while ice cream is still frozen.",
    ],
  },
  {
    id: "4",
    title: "Vegetable Stir Fry",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 20,
    rating: 4.5,
    category: "cooking",
    ingredients: [
      "2 tbsp vegetable oil",
      "2 cloves garlic, minced",
      "1 tbsp ginger, minced",
      "1 bell pepper, sliced",
      "1 carrot, julienned",
      "1 cup broccoli florets",
      "1 cup snap peas",
      "2 tbsp soy sauce",
      "1 tbsp sesame oil",
      "1 tsp honey",
      "Sesame seeds for garnish",
    ],
    instructions: [
      "Heat vegetable oil in a wok or large skillet over high heat.",
      "Add garlic and ginger, stir fry for 30 seconds until fragrant.",
      "Add vegetables and stir fry for 4-5 minutes until crisp-tender.",
      "In a small bowl, mix soy sauce, sesame oil, and honey.",
      "Pour sauce over vegetables and toss to coat.",
      "Cook for another 1-2 minutes until sauce is slightly thickened.",
      "Garnish with sesame seeds and serve hot with rice or noodles.",
    ],
  },
  {
    id: "5",
    title: "Blueberry Muffins",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 30,
    rating: 4.6,
    category: "baking",
    ingredients: [
      "2 cups all-purpose flour",
      "1 tbsp baking powder",
      "1/2 tsp salt",
      "1/2 cup unsalted butter, softened",
      "1 cup granulated sugar",
      "2 large eggs",
      "1 tsp vanilla extract",
      "1/2 cup milk",
      "2 cups fresh blueberries",
      "2 tbsp coarse sugar for topping (optional)",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line a 12-cup muffin tin with paper liners.",
      "In a medium bowl, whisk together flour, baking powder, and salt.",
      "In a large bowl, cream together butter and sugar until light and fluffy.",
      "Beat in eggs one at a time, then stir in vanilla.",
      "Gradually stir flour mixture into butter mixture alternately with milk.",
      "Gently fold in blueberries.",
      "Divide batter evenly among muffin cups and sprinkle with coarse sugar if using.",
      "Bake for 20-25 minutes until golden and a toothpick inserted in center comes out clean.",
    ],
  },
  {
    id: "6",
    title: "Party Nachos Supreme",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 25,
    rating: 4.8,
    category: "party",
    ingredients: [
      "1 large bag tortilla chips",
      "2 cups shredded Mexican cheese blend",
      "1 can (15 oz) black beans, drained and rinsed",
      "1 cup cooked ground beef or chicken (optional)",
      "1 cup diced tomatoes",
      "1/2 cup sliced jalapeños",
      "1/2 cup sliced black olives",
      "1/4 cup chopped green onions",
      "Sour cream, guacamole, and salsa for serving",
    ],
    instructions: [
      "Preheat oven to 350°F (175°C).",
      "Arrange tortilla chips in an even layer on a large baking sheet.",
      "Sprinkle half the cheese over the chips.",
      "Distribute black beans, meat (if using), tomatoes, jalapeños, and olives over the cheese.",
      "Sprinkle remaining cheese on top.",
      "Bake for 10-15 minutes until cheese is melted and bubbly.",
      "Garnish with green onions and serve with sour cream, guacamole, and salsa.",
    ],
  },
  {
    id: "7",
    title: "Lemon Herb Roasted Chicken",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 75,
    rating: 4.7,
    category: "cooking",
    ingredients: [
      "1 whole chicken (4-5 lbs)",
      "2 lemons, 1 sliced and 1 juiced",
      "4 cloves garlic, minced",
      "2 tbsp olive oil",
      "1 tbsp fresh rosemary, chopped",
      "1 tbsp fresh thyme, chopped",
      "1 tsp salt",
      "1/2 tsp black pepper",
      "1 onion, quartered",
    ],
    instructions: [
      "Preheat oven to 425°F (220°C).",
      "Remove giblets from chicken cavity and pat chicken dry with paper towels.",
      "In a small bowl, mix together lemon juice, garlic, olive oil, rosemary, thyme, salt, and pepper.",
      "Rub herb mixture all over chicken, including under the skin.",
      "Stuff chicken cavity with lemon slices and onion quarters.",
      "Tie legs together with kitchen string and tuck wing tips under the body.",
      "Place chicken breast-side up in a roasting pan.",
      "Roast for 1 hour to 1 hour 15 minutes, until juices run clear and internal temperature reaches 165°F (74°C).",
      "Let rest for 10-15 minutes before carving.",
    ],
  },
  {
    id: "8",
    title: "Cinnamon Rolls",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 180,
    rating: 4.9,
    category: "baking",
    ingredients: [
      "For the dough:",
      "4 cups all-purpose flour",
      "1/3 cup granulated sugar",
      "1 tsp salt",
      "1 package (2 1/4 tsp) active dry yeast",
      "1 cup warm milk",
      "1/3 cup butter, melted",
      "2 eggs",
      "For the filling:",
      "1 cup brown sugar, packed",
      "2 1/2 tbsp ground cinnamon",
      "1/3 cup butter, softened",
      "For the frosting:",
      "4 oz cream cheese, softened",
      "1/4 cup butter, softened",
      "1 1/2 cups powdered sugar",
      "1/2 tsp vanilla extract",
    ],
    instructions: [
      "In a large bowl, mix 2 cups of flour, sugar, salt, and yeast.",
      "Add warm milk, melted butter, and eggs. Beat until well combined.",
      "Gradually add remaining flour to form a soft dough.",
      "Knead on a floured surface for 5-10 minutes until smooth and elastic.",
      "Place in a greased bowl, cover, and let rise in a warm place for 1 hour or until doubled in size.",
      "Roll dough into a 16x21 inch rectangle. Spread with softened butter.",
      "Mix brown sugar and cinnamon; sprinkle over buttered dough.",
      "Roll up dough and cut into 12 rolls. Place in a greased 9x13 inch baking pan.",
      "Cover and let rise for 30 minutes or until nearly doubled.",
      "Preheat oven to 350°F (175°C) and bake rolls for 20-25 minutes until golden brown.",
      "While rolls are baking, beat cream cheese, butter, powdered sugar, and vanilla until smooth.",
      "Spread frosting on warm rolls before serving.",
    ],
  },
  {
    id: "9",
    title: "Mini Caprese Skewers",
    image: "/placeholder.svg?height=400&width=600",
    prepTime: 20,
    rating: 4.6,
    category: "party",
    ingredients: [
      "1 pint cherry tomatoes",
      "8 oz fresh mozzarella pearls",
      "1 bunch fresh basil leaves",
      "2 tbsp olive oil",
      "1 tbsp balsamic glaze",
      "Salt and pepper to taste",
      "Wooden skewers or toothpicks",
    ],
    instructions: [
      "Thread a cherry tomato, a basil leaf, and a mozzarella pearl onto each skewer. Repeat until all ingredients are used.",
      "Arrange skewers on a serving platter.",
      "Drizzle with olive oil and balsamic glaze.",
      "Season with salt and pepper.",
      "Serve immediately or refrigerate until ready to serve.",
    ],
  },
]
